import{afterEach,describe,expect,it,vi}from'vitest';import{sessionRepository as r}from'../src/modules/session/session.repository.js';import{remainingSeconds,sessionService as s}from'../src/modules/session/session.service.js';
import{createSessionSchema}from'../src/modules/session/session.schema.js';
const row=(o:Record<string,unknown>={})=>({id:'session-1',user_id:'user-1',episode_id:'episode-1',difficulty:'hard',status:'READY',remaining_questions:6,started_at:new Date().toISOString(),expires_at:new Date(Date.now()+60000).toISOString(),current_suspect_id:null,...o});
const common=()=>{vi.spyOn(r,'states').mockResolvedValue([{suspect_id:'s1',emotion:'neutral',questions_asked:0},{suspect_id:'s2',emotion:'neutral',questions_asked:0},{suspect_id:'s3',emotion:'neutral',questions_asked:0},{suspect_id:'s4',emotion:'neutral',questions_asked:0}]);vi.spyOn(r,'evidence').mockResolvedValue(['e1']);vi.spyOn(r,'clueCount').mockResolvedValue(0)};afterEach(()=>vi.restoreAllMocks());
describe('session lifecycle',()=>{
it('rejects an invalid difficulty',()=>expect(createSessionSchema.safeParse({episodeId:'00000000-0000-4000-8000-000000000001',difficulty:'impossible'}).success).toBe(false));
it('creates from RPC and returns four states, initial evidence, and JJ hard six questions',async()=>{common();vi.spyOn(r,'initialize').mockResolvedValue('session-1');vi.spyOn(r,'findOwned').mockResolvedValue(row());const v=await s.create('user-1',{episodeId:'episode-1',difficulty:'hard'});expect(r.initialize).toHaveBeenCalledWith('user-1','episode-1','hard');expect(v.remainingQuestions).toBe(6);expect(v.suspectStates).toHaveLength(4);expect(v.viewedEvidenceIds).toEqual(['e1'])});
it('blocks another owner',async()=>{vi.spyOn(r,'findOwned').mockResolvedValue(null);await expect(s.get('session-1','other')).rejects.toMatchObject({code:'SESSION_NOT_FOUND'})});
it('computes server remaining time',()=>{expect(remainingSeconds(new Date(11000).toISOString(),1000)).toBe(10)});
it('expires using server time',async()=>{common();vi.spyOn(r,'findOwned').mockResolvedValue(row({expires_at:new Date(Date.now()-1000).toISOString()}));const t=vi.spyOn(r,'transition').mockResolvedValue(row({status:'EXPIRED'}));await expect(s.get('session-1','user-1')).resolves.toMatchObject({status:'EXPIRED',remainingSeconds:0});expect(t).toHaveBeenCalledWith('session-1','user-1','EXPIRED',undefined,['READY','INVESTIGATING','INTERROGATING','DEDUCTION'])});
it('selects only a suspect in the episode with a conditional update',async()=>{common();vi.spyOn(r,'findOwned').mockResolvedValue(row());vi.spyOn(r,'suspectBelongs').mockResolvedValue(true);const t=vi.spyOn(r,'transition').mockResolvedValue(row());await s.selectSuspect('session-1','user-1','s1');expect(t).toHaveBeenCalledWith('session-1','user-1','INTERROGATING','s1',['READY','INVESTIGATING','INTERROGATING'])});
it.each(['COMPLETED','ABANDONED','EXPIRED'])('rejects suspect selection for %s sessions',async(status)=>{vi.spyOn(r,'findOwned').mockResolvedValue(row({status}));await expect(s.selectSuspect('session-1','user-1','s1')).rejects.toMatchObject({code:'SESSION_ALREADY_TERMINATED'});});
it('rejects duplicate deduction',async()=>{vi.spyOn(r,'findOwned').mockResolvedValue(row({status:'DEDUCTION'}));await expect(s.deduction('session-1','user-1')).rejects.toMatchObject({code:'SESSION_ALREADY_IN_DEDUCTION'})});
it('abandons an active session',async()=>{common();vi.spyOn(r,'findOwned').mockResolvedValue(row());const t=vi.spyOn(r,'transition').mockResolvedValue(row({status:'ABANDONED'}));await s.abandon('session-1','user-1');expect(t).toHaveBeenCalledWith('session-1','user-1','ABANDONED',undefined,['READY','INVESTIGATING','INTERROGATING','DEDUCTION'])});
});
