import { afterEach, describe, expect, it, vi } from 'vitest';
import { suspectRepository } from '../src/modules/suspect/suspect.repository.js';
import { suspectService } from '../src/modules/suspect/suspect.service.js';
import { episodeRepository } from '../src/modules/episode/episode.repository.js';
import type { SuspectRecord } from '../src/modules/suspect/suspect.types.js';

const suspect = (index = 1, episodeId = 'episode-1'): SuspectRecord => ({ id: `suspect-${index}`, episodeId, code: `GS-01-S${index}`, name: `용의자 ${index}`, age: 20 + index, occupation: '공개 직업', publicProfile: { summary: '공개 소개' }, victimRelation: '피해자와 공개 관계', displayOrder: index, imageUrl: null });
afterEach(() => vi.restoreAllMocks());

describe('suspect service', () => {
  it('returns four suspects in display order using the resolved episode UUID', async () => { vi.spyOn(episodeRepository, 'findByKey').mockResolvedValue({ id: 'episode-1', code: 'GS-01', title: '종가의 밤', location: null, incidentType: null, synopsis: null, estimatedPlayMinutes: 15, status: 'published', imageUrl: null, progressStatus: null, sceneDescription: null }); vi.spyOn(suspectRepository, 'findByEpisode').mockResolvedValue([suspect(4), suspect(2), suspect(1), suspect(3)]); const result = await suspectService.list('gs-01'); expect(result).toHaveLength(4); expect(result.map((item) => item.displayOrder)).toEqual([1,2,3,4]); expect(suspectRepository.findByEpisode).toHaveBeenCalledWith('episode-1'); });
  it('blocks a suspect from another episode', async () => { vi.spyOn(episodeRepository, 'findByKey').mockResolvedValue({ id: 'episode-1', code: 'GS-01', title: '종가의 밤', location: null, incidentType: null, synopsis: null, estimatedPlayMinutes: 15, status: 'published', imageUrl: null, progressStatus: null, sceneDescription: null }); vi.spyOn(suspectRepository, 'findByKey').mockResolvedValue(null); await expect(suspectService.detail('gs-01', 'JL-01-S1')).rejects.toMatchObject({ code: 'SUSPECT_NOT_FOUND' }); expect(suspectRepository.findByKey).toHaveBeenCalledWith('JL-01-S1', 'episode-1'); });
  it('does not expose routes, culprit, emotion, personality, or private rule data', async () => { vi.spyOn(episodeRepository, 'findByKey').mockResolvedValue({ id: 'episode-1', code: 'GS-01', title: '종가의 밤', location: null, incidentType: null, synopsis: null, estimatedPlayMinutes: 15, status: 'published', imageUrl: null, progressStatus: null, sceneDescription: null }); vi.spyOn(suspectRepository, 'findByKey').mockResolvedValue(suspect()); const result = await suspectService.detail('gs-01', 'GS-01-S1'); const json = JSON.stringify(result); expect(json).not.toContain('actualRoute'); expect(json).not.toContain('claimedRoute'); expect(json).not.toContain('is_culprit'); expect(json).not.toContain('suspect_facts'); expect(result).not.toHaveProperty('episodeId'); expect(result).not.toHaveProperty('initialEmotion'); expect(result).not.toHaveProperty('personality'); });
  it('returns SUSPECT_NOT_FOUND for a missing suspect', async () => { vi.spyOn(episodeRepository, 'findByKey').mockResolvedValue({ id: 'episode-1', code: 'GS-01', title: '종가의 밤', location: null, incidentType: null, synopsis: null, estimatedPlayMinutes: 15, status: 'published', imageUrl: null, progressStatus: null, sceneDescription: null }); vi.spyOn(suspectRepository, 'findByKey').mockResolvedValue(null); await expect(suspectService.detail('gs-01', 'missing')).rejects.toMatchObject({ code: 'SUSPECT_NOT_FOUND' }); });
  it('returns EPISODE_NOT_FOUND for a missing episode', async () => { vi.spyOn(episodeRepository, 'findByKey').mockResolvedValue(null); await expect(suspectService.list('missing')).rejects.toMatchObject({ code: 'EPISODE_NOT_FOUND' }); });
});
